baseURL = "https://bootrako.github.io/"

theme = "hugo-bearblog"

title = "bootrako"
author = "bootrako"
copyright = "Copyright © 2023, bootrako."
languageCode = "en-US"

enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "bootrako's video game programming blog"
  title = "bootrako"
